# Generated by Django 4.2.7 on 2024-07-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greeninitiative',
            old_name='description',
            new_name='information',
        ),
        migrations.AddField(
            model_name='greeninitiative',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
