# Generated by Django 4.2.7 on 2024-07-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_rename_description_greeninitiative_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeninitiativecomment',
            name='personal_views',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
