# Generated by Django 4.2.7 on 2024-07-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_remove_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='person_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
