# Generated by Django 4.2.7 on 2024-07-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_feedback_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='testimonial',
        ),
    ]
