# Generated by Django 5.1.3 on 2024-11-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0010_rename_comment_feedback_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
