# Generated by Django 5.1.3 on 2024-11-19 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_complaint_is_verified_complaint_thumbs_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
